alias vim='nvim'
alias ..='cd ..'
alias vi='vim'
alias home='cd ~'
alias windows='cd "/mnt/c/users/V0402117/OneDrive - Honda/Desktop" '
alias :so='source ~/.bashrc && source ~/.bash_aliases && source ~/.inputrc'
alias sd="cd /home/ && cd \$(find * -type d | fzf)"
alias srd="cd \$(find * -type d | fzf)"
alias ff="vim \$(find * -type f | fzf)"
alias tmls="tmux ls"
alias tma="tmux attach -t"
alias tmns="tmux new -s"
alias pjs='cd "/mnt/c/users/V0402117/OneDrive - Honda/Documents/Projects" '
alias python="python3"
#alias grep="grep -oP"
